version: '3'

services:
  nginx:
    container_name: nginx
    image: kavini/nginx:latest
    # build: 
    #   context: ./nginx
    #   dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app1
    # environment:
    #   - APP_SERVER_IP=${APP_SERVER_IP}
    #   - APP_SERVER_PORT=${APP_SERVER_PORT}

  app1:
    container_name: api_app_1
    image: kavini/app1:latest
    # build: 
    #   context: ./api_app_1
    #   dockerfile: Dockerfile 
    ports:
      - "3000:8030"