version: '3'

services:
  nginx:
    container_name: nginx_proxy
    image: kavini/nginx:$GITHUB_SHA
    # build: 
    #   context: ./nginx
    #   dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app1
    environment:
      - APP_SERVER_IP=${{ secrets.APP_SERVER_IP }}
      - APP_SERVER_PORT=${{ secrets.APP_SERVER_IP }}

  app1:
    container_name: api_app_1
    image: kavini/app1:$GITHUB_SHA
    # build: 
    #   context: ./api_app_1
    #   dockerfile: Dockerfile 
    ports:
      - "3000:8030"