name: Deploy NGINX Proxy and Swagger app

on:
    workflow_dispatch:  # Spustitelný manuálně

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
        APP_SERVER_IP: ${{ secrets.APP_SERVER_IP }}
        APP_SERVER_PORT: ${{ secrets.APP_SERVER_PORT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push app1
      run: |
        docker build -t app1 ./api_app_1
        docker tag app1 ${{ secrets.DOCKERHUB_USERNAME }}/app1:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app1:latest

    - name: Build and push nginx
      run: |
        docker build -t nginx ./nginx
        docker tag nginx ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.APP_SERVER_IP }} "
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/app1:latest
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest
        docker-compose -f docker-compose.yml up -d
        "

    - name: Check if app is running
      run: |
        curl -s ${{ secrets.APP_SERVER_IP }} | grep -q "Swagger UI"